var namespace_mirror =
[
    [ "Authenticators", "namespace_mirror_1_1_authenticators.html", "namespace_mirror_1_1_authenticators" ],
    [ "Cloud", "namespace_mirror_1_1_cloud.html", "namespace_mirror_1_1_cloud" ],
    [ "Discovery", "namespace_mirror_1_1_discovery.html", "namespace_mirror_1_1_discovery" ],
    [ "EditorScripts", "namespace_mirror_1_1_editor_scripts.html", "namespace_mirror_1_1_editor_scripts" ],
    [ "Examples", "namespace_mirror_1_1_examples.html", "namespace_mirror_1_1_examples" ],
    [ "Experimental", "namespace_mirror_1_1_experimental.html", "namespace_mirror_1_1_experimental" ],
    [ "Logging", "namespace_mirror_1_1_logging.html", "namespace_mirror_1_1_logging" ],
    [ "RemoteCalls", "namespace_mirror_1_1_remote_calls.html", "namespace_mirror_1_1_remote_calls" ],
    [ "SimpleWeb", "namespace_mirror_1_1_simple_web.html", "namespace_mirror_1_1_simple_web" ],
    [ "Weaver", "namespace_mirror_1_1_weaver.html", "namespace_mirror_1_1_weaver" ],
    [ "PreprocessorDefine", "class_mirror_1_1_preprocessor_define.html", "class_mirror_1_1_preprocessor_define" ],
    [ "NetworkAnimator", "class_mirror_1_1_network_animator.html", "class_mirror_1_1_network_animator" ],
    [ "NetworkLobbyManager", "class_mirror_1_1_network_lobby_manager.html", null ],
    [ "NetworkLobbyPlayer", "class_mirror_1_1_network_lobby_player.html", null ],
    [ "NetworkMatchChecker", "class_mirror_1_1_network_match_checker.html", "class_mirror_1_1_network_match_checker" ],
    [ "NetworkPingDisplay", "class_mirror_1_1_network_ping_display.html", "class_mirror_1_1_network_ping_display" ],
    [ "NetworkProximityChecker", "class_mirror_1_1_network_proximity_checker.html", "class_mirror_1_1_network_proximity_checker" ],
    [ "NetworkRoomManager", "class_mirror_1_1_network_room_manager.html", "class_mirror_1_1_network_room_manager" ],
    [ "NetworkRoomPlayer", "class_mirror_1_1_network_room_player.html", "class_mirror_1_1_network_room_player" ],
    [ "NetworkSceneChecker", "class_mirror_1_1_network_scene_checker.html", "class_mirror_1_1_network_scene_checker" ],
    [ "NetworkTransform", "class_mirror_1_1_network_transform.html", "class_mirror_1_1_network_transform" ],
    [ "NetworkTransformBase", "class_mirror_1_1_network_transform_base.html", "class_mirror_1_1_network_transform_base" ],
    [ "NetworkTransformChild", "class_mirror_1_1_network_transform_child.html", "class_mirror_1_1_network_transform_child" ],
    [ "EnterPlayModeSettingsCheck", "class_mirror_1_1_enter_play_mode_settings_check.html", null ],
    [ "InspectorHelper", "class_mirror_1_1_inspector_helper.html", "class_mirror_1_1_inspector_helper" ],
    [ "NetworkBehaviourInspector", "class_mirror_1_1_network_behaviour_inspector.html", "class_mirror_1_1_network_behaviour_inspector" ],
    [ "SyncListDrawer", "class_mirror_1_1_sync_list_drawer.html", "class_mirror_1_1_sync_list_drawer" ],
    [ "NetworkInformationPreview", "class_mirror_1_1_network_information_preview.html", "class_mirror_1_1_network_information_preview" ],
    [ "NetworkManagerEditor", "class_mirror_1_1_network_manager_editor.html", "class_mirror_1_1_network_manager_editor" ],
    [ "NetworkScenePostProcess", "class_mirror_1_1_network_scene_post_process.html", "class_mirror_1_1_network_scene_post_process" ],
    [ "SceneDrawer", "class_mirror_1_1_scene_drawer.html", "class_mirror_1_1_scene_drawer" ],
    [ "SyncVarAttributeDrawer", "class_mirror_1_1_sync_var_attribute_drawer.html", "class_mirror_1_1_sync_var_attribute_drawer" ],
    [ "ClientScene", "class_mirror_1_1_client_scene.html", "class_mirror_1_1_client_scene" ],
    [ "Compression", "class_mirror_1_1_compression.html", "class_mirror_1_1_compression" ],
    [ "SyncVarAttribute", "class_mirror_1_1_sync_var_attribute.html", "class_mirror_1_1_sync_var_attribute" ],
    [ "CommandAttribute", "class_mirror_1_1_command_attribute.html", "class_mirror_1_1_command_attribute" ],
    [ "ClientRpcAttribute", "class_mirror_1_1_client_rpc_attribute.html", "class_mirror_1_1_client_rpc_attribute" ],
    [ "TargetRpcAttribute", "class_mirror_1_1_target_rpc_attribute.html", "class_mirror_1_1_target_rpc_attribute" ],
    [ "ServerAttribute", "class_mirror_1_1_server_attribute.html", null ],
    [ "ServerCallbackAttribute", "class_mirror_1_1_server_callback_attribute.html", null ],
    [ "ClientAttribute", "class_mirror_1_1_client_attribute.html", null ],
    [ "ClientCallbackAttribute", "class_mirror_1_1_client_callback_attribute.html", null ],
    [ "SceneAttribute", "class_mirror_1_1_scene_attribute.html", null ],
    [ "ShowInInspectorAttribute", "class_mirror_1_1_show_in_inspector_attribute.html", null ],
    [ "ExponentialMovingAverage", "class_mirror_1_1_exponential_moving_average.html", "class_mirror_1_1_exponential_moving_average" ],
    [ "ULocalConnectionToClient", "class_mirror_1_1_u_local_connection_to_client.html", "class_mirror_1_1_u_local_connection_to_client" ],
    [ "LogFilter", "class_mirror_1_1_log_filter.html", "class_mirror_1_1_log_filter" ],
    [ "LogFactory", "class_mirror_1_1_log_factory.html", "class_mirror_1_1_log_factory" ],
    [ "ILoggerExtensions", "class_mirror_1_1_i_logger_extensions.html", "class_mirror_1_1_i_logger_extensions" ],
    [ "MessagePacker", "class_mirror_1_1_message_packer.html", "class_mirror_1_1_message_packer" ],
    [ "IMessageBase", "interface_mirror_1_1_i_message_base.html", null ],
    [ "MessageBase", "class_mirror_1_1_message_base.html", null ],
    [ "NetworkMessage", "interface_mirror_1_1_network_message.html", null ],
    [ "ErrorMessage", "struct_mirror_1_1_error_message.html", "struct_mirror_1_1_error_message" ],
    [ "ReadyMessage", "struct_mirror_1_1_ready_message.html", null ],
    [ "NotReadyMessage", "struct_mirror_1_1_not_ready_message.html", null ],
    [ "AddPlayerMessage", "struct_mirror_1_1_add_player_message.html", null ],
    [ "DisconnectMessage", "struct_mirror_1_1_disconnect_message.html", null ],
    [ "ConnectMessage", "struct_mirror_1_1_connect_message.html", null ],
    [ "SceneMessage", "struct_mirror_1_1_scene_message.html", "struct_mirror_1_1_scene_message" ],
    [ "CommandMessage", "struct_mirror_1_1_command_message.html", "struct_mirror_1_1_command_message" ],
    [ "RpcMessage", "struct_mirror_1_1_rpc_message.html", "struct_mirror_1_1_rpc_message" ],
    [ "SpawnMessage", "struct_mirror_1_1_spawn_message.html", "struct_mirror_1_1_spawn_message" ],
    [ "ObjectSpawnStartedMessage", "struct_mirror_1_1_object_spawn_started_message.html", null ],
    [ "ObjectSpawnFinishedMessage", "struct_mirror_1_1_object_spawn_finished_message.html", null ],
    [ "ObjectDestroyMessage", "struct_mirror_1_1_object_destroy_message.html", "struct_mirror_1_1_object_destroy_message" ],
    [ "ObjectHideMessage", "struct_mirror_1_1_object_hide_message.html", "struct_mirror_1_1_object_hide_message" ],
    [ "UpdateVarsMessage", "struct_mirror_1_1_update_vars_message.html", "struct_mirror_1_1_update_vars_message" ],
    [ "NetworkPingMessage", "struct_mirror_1_1_network_ping_message.html", "struct_mirror_1_1_network_ping_message" ],
    [ "NetworkPongMessage", "struct_mirror_1_1_network_pong_message.html", "struct_mirror_1_1_network_pong_message" ],
    [ "UnityEventNetworkConnection", "class_mirror_1_1_unity_event_network_connection.html", null ],
    [ "NetworkAuthenticator", "class_mirror_1_1_network_authenticator.html", "class_mirror_1_1_network_authenticator" ],
    [ "NetworkBehaviour", "class_mirror_1_1_network_behaviour.html", "class_mirror_1_1_network_behaviour" ],
    [ "NetworkClient", "class_mirror_1_1_network_client.html", "class_mirror_1_1_network_client" ],
    [ "NetworkConnection", "class_mirror_1_1_network_connection.html", "class_mirror_1_1_network_connection" ],
    [ "NetworkConnectionToClient", "class_mirror_1_1_network_connection_to_client.html", "class_mirror_1_1_network_connection_to_client" ],
    [ "NetworkConnectionToServer", "class_mirror_1_1_network_connection_to_server.html", "class_mirror_1_1_network_connection_to_server" ],
    [ "NetworkDiagnostics", "class_mirror_1_1_network_diagnostics.html", "class_mirror_1_1_network_diagnostics" ],
    [ "NetworkIdentity", "class_mirror_1_1_network_identity.html", "class_mirror_1_1_network_identity" ],
    [ "NetworkManager", "class_mirror_1_1_network_manager.html", "class_mirror_1_1_network_manager" ],
    [ "NetworkManagerHUD", "class_mirror_1_1_network_manager_h_u_d.html", "class_mirror_1_1_network_manager_h_u_d" ],
    [ "Reader", "class_mirror_1_1_reader.html", "class_mirror_1_1_reader" ],
    [ "NetworkReader", "class_mirror_1_1_network_reader.html", "class_mirror_1_1_network_reader" ],
    [ "NetworkReaderExtensions", "class_mirror_1_1_network_reader_extensions.html", "class_mirror_1_1_network_reader_extensions" ],
    [ "PooledNetworkReader", "class_mirror_1_1_pooled_network_reader.html", "class_mirror_1_1_pooled_network_reader" ],
    [ "NetworkReaderPool", "class_mirror_1_1_network_reader_pool.html", "class_mirror_1_1_network_reader_pool" ],
    [ "NetworkServer", "class_mirror_1_1_network_server.html", "class_mirror_1_1_network_server" ],
    [ "NetworkStartPosition", "class_mirror_1_1_network_start_position.html", "class_mirror_1_1_network_start_position" ],
    [ "NetworkTime", "class_mirror_1_1_network_time.html", "class_mirror_1_1_network_time" ],
    [ "NetworkVisibility", "class_mirror_1_1_network_visibility.html", "class_mirror_1_1_network_visibility" ],
    [ "Writer", "class_mirror_1_1_writer.html", "class_mirror_1_1_writer" ],
    [ "NetworkWriter", "class_mirror_1_1_network_writer.html", "class_mirror_1_1_network_writer" ],
    [ "NetworkWriterExtensions", "class_mirror_1_1_network_writer_extensions.html", "class_mirror_1_1_network_writer_extensions" ],
    [ "PooledNetworkWriter", "class_mirror_1_1_pooled_network_writer.html", "class_mirror_1_1_pooled_network_writer" ],
    [ "NetworkWriterPool", "class_mirror_1_1_network_writer_pool.html", "class_mirror_1_1_network_writer_pool" ],
    [ "Pool", "class_mirror_1_1_pool.html", "class_mirror_1_1_pool" ],
    [ "StringHash", "class_mirror_1_1_string_hash.html", "class_mirror_1_1_string_hash" ],
    [ "SyncIDictionary", "class_mirror_1_1_sync_i_dictionary.html", "class_mirror_1_1_sync_i_dictionary" ],
    [ "SyncDictionary", "class_mirror_1_1_sync_dictionary.html", "class_mirror_1_1_sync_dictionary" ],
    [ "SyncListString", "class_mirror_1_1_sync_list_string.html", null ],
    [ "SyncListFloat", "class_mirror_1_1_sync_list_float.html", null ],
    [ "SyncListInt", "class_mirror_1_1_sync_list_int.html", null ],
    [ "SyncListUInt", "class_mirror_1_1_sync_list_u_int.html", null ],
    [ "SyncListBool", "class_mirror_1_1_sync_list_bool.html", null ],
    [ "SyncList", "class_mirror_1_1_sync_list.html", "class_mirror_1_1_sync_list" ],
    [ "SyncObject", "interface_mirror_1_1_sync_object.html", "interface_mirror_1_1_sync_object" ],
    [ "SyncSet", "class_mirror_1_1_sync_set.html", "class_mirror_1_1_sync_set" ],
    [ "SyncHashSet", "class_mirror_1_1_sync_hash_set.html", "class_mirror_1_1_sync_hash_set" ],
    [ "SyncSortedSet", "class_mirror_1_1_sync_sorted_set.html", "class_mirror_1_1_sync_sorted_set" ],
    [ "FallbackTransport", "class_mirror_1_1_fallback_transport.html", "class_mirror_1_1_fallback_transport" ],
    [ "LLAPITransport", "class_mirror_1_1_l_l_a_p_i_transport.html", "class_mirror_1_1_l_l_a_p_i_transport" ],
    [ "MiddlewareTransport", "class_mirror_1_1_middleware_transport.html", "class_mirror_1_1_middleware_transport" ],
    [ "MultiplexTransport", "class_mirror_1_1_multiplex_transport.html", "class_mirror_1_1_multiplex_transport" ],
    [ "TelepathyTransport", "class_mirror_1_1_telepathy_transport.html", "class_mirror_1_1_telepathy_transport" ],
    [ "Transport", "class_mirror_1_1_transport.html", "class_mirror_1_1_transport" ],
    [ "Channels", "class_mirror_1_1_channels.html", "class_mirror_1_1_channels" ],
    [ "ConnectState", "namespace_mirror.html#aa96319d195bb46cee93ba4cbdf4f514b", [
      [ "None", "namespace_mirror.html#aa96319d195bb46cee93ba4cbdf4f514ba6adf97f83acf6453d4a6a4b1070f3754", null ],
      [ "Connecting", "namespace_mirror.html#aa96319d195bb46cee93ba4cbdf4f514bae321c53b354930ba96f0243e652df458", null ],
      [ "Connected", "namespace_mirror.html#aa96319d195bb46cee93ba4cbdf4f514ba2ec0d16e4ca169baedb9b2d50ec5c6d7", null ],
      [ "Disconnected", "namespace_mirror.html#aa96319d195bb46cee93ba4cbdf4f514baef70e46fd3bbc21e3e1f0b6815e750c0", null ]
    ] ],
    [ "MirrorInvokeType", "namespace_mirror.html#a966c980809ea6a100d1971366de3ed69", [
      [ "Command", "namespace_mirror.html#a966c980809ea6a100d1971366de3ed69aee97be03cb04119af45014d815621ce1", null ],
      [ "ClientRpc", "namespace_mirror.html#a966c980809ea6a100d1971366de3ed69a9e5f77e3b815016923048c210dde705f", null ]
    ] ],
    [ "NetworkManagerMode", "namespace_mirror.html#a1956ffe54926cf889f04ff03d248009b", [
      [ "Offline", "namespace_mirror.html#a1956ffe54926cf889f04ff03d248009ba8d9da4bc0e49a50e09ac9f7e56789d39", null ],
      [ "ServerOnly", "namespace_mirror.html#a1956ffe54926cf889f04ff03d248009baab2bffbd2a02d6b8390aac7945477272", null ],
      [ "ClientOnly", "namespace_mirror.html#a1956ffe54926cf889f04ff03d248009ba186244edf2711a5111ac0cc3dd007b01", null ],
      [ "Host", "namespace_mirror.html#a1956ffe54926cf889f04ff03d248009bac2ca16d048ec66e04bca283eab048ec2", null ]
    ] ],
    [ "PlayerSpawnMethod", "namespace_mirror.html#a23132665b6a9f18117f09ce19aec9609", [
      [ "Random", "namespace_mirror.html#a23132665b6a9f18117f09ce19aec9609a64663f4646781c9c0110838b905daa23", null ],
      [ "RoundRobin", "namespace_mirror.html#a23132665b6a9f18117f09ce19aec9609a91a63281bd2e647fe3b92d1d22cd3380", null ]
    ] ],
    [ "SceneOperation", "namespace_mirror.html#a7a51f9c6460df8b7bbbe27394905a80e", [
      [ "Normal", "namespace_mirror.html#a7a51f9c6460df8b7bbbe27394905a80ea960b44c579bc2f6818d2daaf9e4c16f0", null ],
      [ "LoadAdditive", "namespace_mirror.html#a7a51f9c6460df8b7bbbe27394905a80ea161690c7fa376c75d1e280e352a3f02a", null ],
      [ "UnloadAdditive", "namespace_mirror.html#a7a51f9c6460df8b7bbbe27394905a80eacd2901f20b7a3c3e4d29d4287bf94a0e", null ]
    ] ],
    [ "SyncMode", "namespace_mirror.html#ac9acfe9461893a0d1ebc0eef63d1a6ff", [
      [ "Observers", "namespace_mirror.html#ac9acfe9461893a0d1ebc0eef63d1a6ffa1b3b22fe46ee3a448828dea57f838bd7", null ],
      [ "Owner", "namespace_mirror.html#ac9acfe9461893a0d1ebc0eef63d1a6ffab6f4a2ec6356bbd56d49f2096bf9d3d3", null ]
    ] ],
    [ "Version", "namespace_mirror.html#a245bc5323b571ec7072e30dfaac87a2d", [
      [ "Current", "namespace_mirror.html#a245bc5323b571ec7072e30dfaac87a2da222a267cc5778206b253be35ee3ddab5", null ]
    ] ],
    [ "NetworkMessageDelegate", "namespace_mirror.html#ad0b18454a149604c67281984c2e21123", null ],
    [ "SpawnDelegate", "namespace_mirror.html#a0af974c5767080712e90a27638b20f2a", null ],
    [ "SpawnHandlerDelegate", "namespace_mirror.html#ad646c9ec125f040194879a564ef54974", null ],
    [ "UnSpawnDelegate", "namespace_mirror.html#a1c4202cf4f4d829c5de08fe7c96b81f1", null ]
];